name: Build openwrt 25.12

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '是否开启SSH配置固件 (true/false)'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-25.12
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: openwrt25.config
  DIY_P1_SH: diy-part1.sh
